### ISSUE TITLE
SubStorage fails with ROOT key 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#201]
`SubStorage` from `ROOT` key fails to save content with `IllegalStateException`, I do not think this is correct behavior: `SubStorage` should process such case properly, as it's user I do not want to care whether my prefix is `ROOT` or not.

**Comment by olenagerasimova** [comment]
@artipie/contributors what do you think? Maybe someone wants to fix it?

**Comment by 0crat** [comment]
The job [#201](https://github.com/artipie/asto/issues/201) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/46af7b0b-9c17-4fc6-a9e4-76f5043c6402); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@olenagerasimova actually it's not about `SubStorage`, only `InMemoryStorage` supports `Key.ROOT` key to save, both `FileStorage` and `S3Storage` doesn't support it. If you use `SubStorage` over `FileStorage`. I checked it with `StorageSaveAndLoadTest.shouldSave` test with replaced key with `ROOT`:
```
shouldSave(Storage)
  [InMemoryStorage] (passed)
  [InMemoryTransaction] (passed)
  [S3Storage] (failed)
  [SubStorage] (passed)
  [FileStorage] (failed)
```

I think we should not support `ROOT` key for `save`, because it's empty key and may not be supported by storage implementations, e.g. `FileStorage` can't save file to `/` and `S3Storage` can't save it to bucket root.

**Comment by olenagerasimova** [comment]
not valid anymore
